# This is a basic workflow to help you get started with Actions

name: SyncFiles

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Sync-Redirect-Config:
    if: ${{ github.ref == 'refs/heads/redirect' }}    
    
    # The type of runner that the job will run on
    runs-on: self-hosted
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
         # Runs a set of commands using the runners shell
      - name: Get Source
        run: |
          cd /home/ubuntu
          [ -d demo-pages-miscellaneous ] && rm -rf demo-pages-miscellaneous
          git clone --depth 1 -b redirect https://github.com/Dynamsoft/demo-pages-miscellaneous.git 
          
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_DEMO_SERVER }}
          username: ${{ secrets.FTP_DEMO_USERNAME }}
          password: ${{ secrets.FTP_DEMO_PASSWORD }}
          port: 21 
          local-dir: /home/ubuntu/demo-pages-miscellaneous/link-redirect-config/
          server-dir: /Demo.dynamsoft.com/solutions/passport-scanner/
      - name: List files before sync
        run: ls -R /home/ubuntu/demo-pages-miscellaneous/link-redirect-config/
        
      - name: List files after sync
        run: ls -R /Demo.dynamsoft.com/solutions/mrz-scanner
        
